name: Marche Kaban
favicon: null
layout_spectrum: 0.95527
typography_spectrum: 0.025710929417982697
title: Marche Kaban
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b8b8b8'
    - '#010101'
    - '#3c363a'
    - '#807a7a'
    - '#7f1720'
  brandStrength: 0.125
  lightness: 0.44154586899094284
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
